services:
    app.menu_builder:
        class: AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    app.form.type.account:
        class: AppBundle\Form\Type\AccountCreateType
        tags:
            - { name: form.type, alias: accountCreate }

    app.form.type.accountType:
        class: AppBundle\Form\Type\AccountTypeType
        tags:
            - { name: form.type, alias: accountType }

    validator.unique.unique_user_type_validator:
        class: AppBundle\Validator\Constraints\UniqueUserTypeValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: unique_user_type_validator }
