services:
    # Menus
    app.menu_builder:
        class: AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    # Form Types
    app.form.type.account:
        class: AppBundle\Form\Type\AccountCreateType
        arguments:
            - "@security.token_storage"
        tags:
            - { name: form.type, alias: accountCreate }

    app.form.type.accountType:
        class: AppBundle\Form\Type\AccountTypeType
        tags:
            - { name: form.type, alias: accountType }

    app.form.type.categoryType:
        class: AppBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: category }

    app.form.type.bill:
        class: AppBundle\Form\Type\BillType
        arguments:
            - "@security.token_storage"
        tags:
            - { name: form.type, alias: bill }

    app.form.type.reconcile:
        class: AppBundle\Form\Type\ReconcileType
        arguments:
            - "@security.token_storage"
        tags:
            - { name: form.type, alias: reconcile }

    app.form.type.payment:
        class: AppBundle\Form\Type\TransactionType
        arguments:
            - "@security.token_storage"
            - "@router"
        tags:
            - { name: form.type, alias: transaction }

    app.form.type.deposit:
        class: AppBundle\Form\Type\DepositType
        arguments:
            - "@security.token_storage"
            - "@router"
        tags:
            - { name: form.type, alias: deposit }

    app.form.type.account.filter:
        class: AppBundle\Form\Type\AccountFilterType
        arguments:
            - "@security.token_storage"
        tags:
            - { name: form.type, alias: accountFilter }

    app.form.type.reconcile:
        class: AppBundle\Form\Type\ReconcileType
        tags:
            - { name: form.type, alias: reconcile }

    # Validators
    validator.unique.unique_name_validator:
        class: AppBundle\Validator\Constraints\UniqueNameValidator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
        tags:
            - { name: validator.constraint_validator, alias: unique_name_validator }

    validator.transaction.bill_or_payee_validator:
        class: AppBundle\Validator\Constraints\BillOrPayeeValidator
        arguments:
            - "@braincrafted_bootstrap.flash"
        tags:
            - { name: validator.constraint_validator, alias: bill_or_payee_validator }

    # Doctrine Listeners
    app.transaction.listener:
        class: AppBundle\EventListener\TransactionProcessingListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
